### ISSUE TITLE
No contact information

### ISSUE THREAD

**Issue by detly** [GCalToolkit/GCalToolkit#1]
The help and other parts of the website refer to a "contact page" if a user wishes to contact you, but there is no such page. In fact, there seems to be no email address or contact form anywhere on the website.

**Comment by GCalToolkit** [comment]
Hi Jason, thanks for pointing that out - I recently revamped the website and to reduce spam I replaced the contact page with a "live chat"/"email" contact button that you should see on every page:

![Screenshot_2024-03-25-11-22-08-700_com android chrome-edit](https://github.com/GCalToolkit/GCalToolkit/assets/23053190/0e8b2c46-3859-4266-852f-2754395506d8)

**Comment by detly** [comment]
Ah, I didn't see that on desktop, using Firefox 124.0 (64-bit) installed via Snap on Ubuntu 23.10.

I checked in private browsing mode, and indeed the icon appeared. It turns out it was being filtered out by the Privacy Badger add-on, which has a rule for `app.purechat.com`. I can allow it for your site, but maybe this information can help more generally too.

**Comment by GCalToolkit** [comment]
Good catch - I'll add another contact method so that doesn't happen to anyone else. Thanks!
